In [6]:
import numpy as np
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

print("OUTPUT\n")

arr = np.array([1,2,3,4,5])
columns = 4
op_matx_dec_order = gen_vander_matrix(arr,columns,False)
op_matx_inc_order = gen_vander_matrix(arr,columns,True)

print("The input array is:",arr,"\n")
print("Number of columns in output matrix should be:",columns,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")


OUTPUT

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 



In [10]:
def mov_avg(x, w):
    for i in range(len(x)-(w-1)):
        yield sum(np.ones(w) * x[i:i+w]) / w 

x=  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
list(mov_avg(x, 3))


[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]